BEGIN;

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS places CASCADE;
DROP TABLE IF EXISTS flags CASCADE;

CREATE TABLE users(
  id SERIAL PRIMARY KEY,
  user_name VARCHAR(100) NOT NULL,
  password CHAR(60) NOT NULL);

CREATE TABLE places(
  id VARCHAR(100) PRIMARY KEY,
  place_name TEXT NOT NULL,
  address VARCHAR(100) NOT NULL);

CREATE TABLE flags(
  id SERIAL PRIMARY KEY,
  flag_name VARCHAR(10),
  place_id VARCHAR(100) REFERENCES places,
  user_id INTEGER REFERENCES users);

COMMIT;
