BEGIN;

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS places CASCADE;
DROP TABLE IF EXISTS flags CASCADE;

CREATE TABLE users(
  id SERIAL PRIMARY KEY,
  user_name VARCHAR(100) NOT NULL,
  password CHAR(60) NOT NULL);

CREATE TABLE flags(
  id SERIAL PRIMARY KEY,
  flag_name VARCHAR(10) NOT NULL,
  place_id VARCHAR(100) NOT NULL,
  user_id INTEGER REFERENCES users,
  date_created TIMESTAMP NOT NULL DEFAULT NOW());

COMMIT;
